name: 'CI'
description: 'Action'
branding:
  icon: activity
  color: orange
inputs:
  owner:
    description:
      'CaltexGames'
    required: true
  name:
    description:
      'SpeedLevelBuilder'
    required: true
  branch:
    description:
      'main'
    required: true
  dir:
    description:
      'SpeedLevelBuilder'
    required: false
    default: '/github/workspace'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
  - '-o'
  - ${{ inputs.owner }}
  - '-n'
  - ${{ inputs.name }}
  - '-b'
  - ${{ inputs.branch }}
  - '-d'
  - ${{ inputs.dir }}